spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clone_facebook
    username: root
    password: nam123456
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

